### ISSUE TITLE
Race condition in `require 'cloudinary'`

### ISSUE THREAD

**Issue by johnvh** [cloudinary/cloudinary_gem#127]
There is a race condition when requiring the cloudinary gem. `cloudinary/railtie` must be required **after** `cloudinary`. If it's required **during** the load of `cloudinary`, then an exception is throw:

```
/Users/john/dev/foo/path/ruby/2.1.0/gems/cloudinary-1.0.77/lib/cloudinary/helper.rb:237:in `block in included': undefined method `config' for Cloudinary:Module (NoMethodError)
	from /Users/john/dev/foo/path/ruby/2.1.0/gems/cloudinary-1.0.77/lib/cloudinary/helper.rb:233:in `class_eval'
	from /Users/john/dev/foo/path/ruby/2.1.0/gems/cloudinary-1.0.77/lib/cloudinary/helper.rb:233:in `included'
	from /Users/john/dev/foo/path/ruby/2.1.0/gems/cloudinary-1.0.77/lib/cloudinary/railtie.rb:6:in `include'
	from /Users/john/dev/foo/path/ruby/2.1.0/gems/cloudinary-1.0.77/lib/cloudinary/railtie.rb:6:in `block in <class:Railtie>'
	from /Users/john/dev/foo/path/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/lazy_load_hooks.rb:36:in `call'
	from /Users/john/dev/foo/path/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/lazy_load_hooks.rb:36:in `execute_hook'
	from /Users/john/dev/foo/path/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/lazy_load_hooks.rb:28:in `block in on_load'
	from /Users/john/dev/foo/path/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/lazy_load_hooks.rb:27:in `each'
	from /Users/john/dev/foo/path/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/lazy_load_hooks.rb:27:in `on_load'
	from /Users/john/dev/foo/path/ruby/2.1.0/gems/railties-4.1.6/lib/rails/railtie/configuration.rb:69:in `after_initialize'
	from /Users/john/dev/foo/path/ruby/2.1.0/gems/cloudinary-1.0.77/lib/cloudinary/railtie.rb:5:in `<class:Railtie>'
	from /Users/john/dev/foo/path/ruby/2.1.0/gems/cloudinary-1.0.77/lib/cloudinary/railtie.rb:1:in `<top (required)>'
	from /Users/john/dev/foo/path/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/dependencies.rb:247:in `require'
	from /Users/john/dev/foo/path/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/dependencies.rb:247:in `block in require'
	from /Users/john/dev/foo/path/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/dependencies.rb:232:in `load_dependency'
	from /Users/john/dev/foo/path/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/dependencies.rb:247:in `require'
	from /Users/john/dev/foo/path/ruby/2.1.0/gems/cloudinary-1.0.77/lib/cloudinary.rb:12:in `<top (required)>'
	from /Users/john/dev/foo/path/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/dependencies.rb:247:in `require'
	from /Users/john/dev/foo/path/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/dependencies.rb:247:in `block in require'
	from /Users/john/dev/foo/path/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/dependencies.rb:232:in `load_dependency'
	from /Users/john/dev/foo/path/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/dependencies.rb:247:in `require'
	from /Users/john/dev/foo/lib/foo/bar.rb:1:in `<top (required)>'
	from /Users/john/dev/foo/path/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/dependencies.rb:247:in `require'
	from /Users/john/dev/foo/path/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/dependencies.rb:247:in `block in require'
	from /Users/john/dev/foo/path/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/dependencies.rb:232:in `load_dependency'
	from /Users/john/dev/foo/path/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/dependencies.rb:247:in `require'
	from /Users/john/dev/foo/test/lib/foo/bar_test.rb:1:in `<top (required)>'
	from /Users/john/dev/foo/path/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/dependencies.rb:247:in `require'
	from /Users/john/dev/foo/path/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/dependencies.rb:247:in `block in require'
	from /Users/john/dev/foo/path/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/dependencies.rb:232:in `load_dependency'
	from /Users/john/dev/foo/path/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/dependencies.rb:247:in `require'
	from /Users/john/dev/foo/path/ruby/2.1.0/gems/rake-10.3.2/lib/rake/rake_test_loader.rb:10:in `block (2 levels) in <main>'
	from /Users/john/dev/foo/path/ruby/2.1.0/gems/rake-10.3.2/lib/rake/rake_test_loader.rb:9:in `each'
	from /Users/john/dev/foo/path/ruby/2.1.0/gems/rake-10.3.2/lib/rake/rake_test_loader.rb:9:in `block in <main>'
	from /Users/john/dev/foo/path/ruby/2.1.0/gems/rake-10.3.2/lib/rake/rake_test_loader.rb:4:in `select'
	from /Users/john/dev/foo/path/ruby/2.1.0/gems/rake-10.3.2/lib/rake/rake_test_loader.rb:4:in `<main>'
rake aborted!
Command failed with status (1): [ruby -I"lib:lib:test" -I"/Users/john/dev/foo/path/ruby/2.1.0/gems/rake-10.3.2/lib" "/Users/john/dev/foo/path/ruby/2.1.0/gems/rake-10.3.2/lib/rake/rake_test_loader.rb" "test/**/*_test.rb" ]
```

See [`cloudinary.rb` line 12](https://github.com/cloudinary/cloudinary_gem/blob/1.0.77/lib/cloudinary.rb#L12):

```ruby
# lib/cloudinary.rb
require "cloudinary/railtie" if defined?(Rails) && defined?(Rails::Railtie)
```

If the condition is met there, and `cloudinary/railtie` is required, then [`CloudinaryHelper.included`](https://github.com/cloudinary/cloudinary_gem/blob/1.0.77/lib/cloudinary/helper.rb#L231) ends up running, as it's included in `ActionView::Base`. If the condition on [line #237 of `CloudinaryHelper.included`](https://github.com/cloudinary/cloudinary_gem/blob/1.0.77/lib/cloudinary/helper.rb#L237) gets to the last expression - `Cloudinary.config.enhance_image_tag` - an exception is raised, as `Cloudinary.config` has not been defined yet... it's [defined later on in `cloudinary.rb`](https://github.com/cloudinary/cloudinary_gem/blob/1.0.77/lib/cloudinary.rb#L42).

**Comment by tocker** [comment]
Hi @johnvh,
Can we close this issue?
