### ISSUE TITLE
Exception 504 on Heroku

### ISSUE THREAD

**Issue by quatermain** [cloudinary/cloudinary_gem#179]
Hi, I use this gem for my page and I didn't have any issue until now. It started a few days ago (maybe more) and I get this error. I have Rails 4.2.4 and 1.1.0 version of this gem. I didn't do any changes in my code before it stoped working. I can upload image without problem sometimes, I get this error maybe in 2 attempts from 5

My uploader:
```
class FeatureImagePostUploader < CarrierWave::Uploader::Base

  include CarrierWave::MiniMagick
  include Cloudinary::CarrierWave

  process tags: ['post_feature_image']

  version :thumb do
    resize_to_fit(50, 50)
  end

  version :show do
    resize_to_fill(735, 400)
  end

  version :top_banner do
    # resize_to_fit(750,420)
    resize_to_fill(750,377, 'south_west')
  end

  version :top_list do
    resize_to_fill(73,73, 'south_west')
  end

  version :top_three do
    resize_to_fit(360,205)
  end

  version :index_blog_thumb do
    resize_to_fill(263,184, 'south_west')
  end

  version :blog_thumb do
    resize_to_fill(300,210, 'south_west')
  end

  version :destination_index do
    resize_to_fill(358,220, 'south_west')
  end

  def extension_white_list
    %w(jpg jpeg gif png)
  end

  def public_id
    if model.respond_to?('slug')
      model.slug
    else
      model.id
    end
  end

end
```

Error:
```
 CloudinaryException (Server returned unexpected status code - 504 - ):
   vendor/bundle/ruby/2.2.0/gems/cloudinary-1.1.0/lib/cloudinary/uploader.rb:285:in `block in call_api'
   vendor/bundle/ruby/2.2.0/gems/rest-client-1.8.0/lib/restclient/request.rb:493:in `call'
   vendor/bundle/ruby/2.2.0/gems/rest-client-1.8.0/lib/restclient/request.rb:493:in `process_result'
   vendor/bundle/ruby/2.2.0/gems/rest-client-1.8.0/lib/restclient/request.rb:421:in `block in transmit'
   vendor/ruby-2.2.1/lib/ruby/2.2.0/net/http.rb:853:in `start'
   vendor/bundle/ruby/2.2.0/gems/rest-client-1.8.0/lib/restclient/request.rb:413:in `transmit'
   vendor/bundle/ruby/2.2.0/gems/rest-client-1.8.0/lib/restclient/request.rb:176:in `execute'
   vendor/bundle/ruby/2.2.0/gems/rest-client-1.8.0/lib/restclient/request.rb:41:in `execute'
   vendor/bundle/ruby/2.2.0/gems/cloudinary-1.1.0/lib/cloudinary/uploader.rb:283:in `call_api'
   vendor/bundle/ruby/2.2.0/gems/cloudinary-1.1.0/lib/cloudinary/uploader.rb:70:in `upload'
   vendor/bundle/ruby/2.2.0/gems/cloudinary-1.1.0/lib/cloudinary/carrier_wave/storage.rb:38:in `store!'
   vendor/bundle/ruby/2.2.0/gems/carrierwave-0.10.0/lib/carrierwave/uploader/store.rb:59:in `block in store!'
   vendor/bundle/ruby/2.2.0/gems/carrierwave-0.10.0/lib/carrierwave/uploader/callbacks.rb:17:in `with_callbacks'
   vendor/bundle/ruby/2.2.0/gems/carrierwave-0.10.0/lib/carrierwave/uploader/store.rb:58:in `store!'
   vendor/bundle/ruby/2.2.0/gems/carrierwave-0.10.0/lib/carrierwave/mount.rb:375:in `store!'
   vendor/bundle/ruby/2.2.0/gems/carrierwave-0.10.0/lib/carrierwave/mount.rb:207:in `store_feature_image!'
   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:432:in `block in make_lambda'
   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:228:in `call'
   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:228:in `block in halting_and_conditional'
   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:506:in `call'
   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:506:in `block in call'
   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:506:in `each'
   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:506:in `call'
   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:778:in `_run_save_callbacks'
   vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/callbacks.rb:302:in `create_or_update'
   vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/persistence.rb:120:in `save'
   vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/validations.rb:37:in `save'
   vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/attribute_methods/dirty.rb:21:in `save'
   vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/transactions.rb:286:in `block (2 levels) in save'
   vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/transactions.rb:351:in `block in with_transaction_returning_status'
   vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
   vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
   vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
   vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/transactions.rb:220:in `transaction'
   vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/transactions.rb:348:in `with_transaction_returning_status'
   vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/transactions.rb:286:in `block in save'
   vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/transactions.rb:301:in `rollback_active_record_state!'
   vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/transactions.rb:285:in `save'
   vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-3.14.0.305/lib/new_relic/agent/instrumentation/active_record_helper.rb:26:in `block in save'
   vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-3.14.0.305/lib/new_relic/agent/transaction.rb:836:in `with_database_metric_name'
   vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-3.14.0.305/lib/new_relic/agent.rb:572:in `with_database_metric_name'
   vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-3.14.0.305/lib/new_relic/agent/instrumentation/active_record_helper.rb:25:in `save'
   vendor/bundle/ruby/2.2.0/bundler/gems/activeadmin-9005b67e6f2a/lib/active_admin/resource_controller/data_access.rb:160:in `block in save_resource'
   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/core_ext/object/try.rb:77:in `call'
   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/core_ext/object/try.rb:77:in `public_send'
   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/core_ext/object/try.rb:77:in `try!'
   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/core_ext/object/try.rb:63:in `try'
   vendor/bundle/ruby/2.2.0/bundler/gems/activeadmin-9005b67e6f2a/lib/active_admin/callbacks.rb:79:in `block (2 levels) in define_active_admin_callbacks'
   vendor/bundle/ruby/2.2.0/bundler/gems/activeadmin-9005b67e6f2a/lib/active_admin/resource_controller/data_access.rb:159:in `save_resource'
   vendor/bundle/ruby/2.2.0/bundler/gems/activeadmin-9005b67e6f2a/lib/active_admin/resource_controller/data_access.rb:149:in `block in create_resource'
   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/core_ext/object/try.rb:77:in `call'
   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/core_ext/object/try.rb:77:in `public_send'
   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/core_ext/object/try.rb:77:in `try!'
   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/core_ext/object/try.rb:63:in `try'
   vendor/bundle/ruby/2.2.0/bundler/gems/activeadmin-9005b67e6f2a/lib/active_admin/callbacks.rb:79:in `block (2 levels) in define_active_admin_callbacks'
   vendor/bundle/ruby/2.2.0/bundler/gems/activeadmin-9005b67e6f2a/lib/active_admin/resource_controller/data_access.rb:148:in `create_resource'
   vendor/bundle/ruby/2.2.0/gems/inherited_resources-1.6.0/lib/inherited_resources/actions.rb:33:in `create'
   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.4/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.4/lib/abstract_controller/base.rb:198:in `process_action'
   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.4/lib/action_controller/metal/rendering.rb:10:in `process_action'
   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.4/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:117:in `call'
   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:117:in `call'
   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:505:in `call'
   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:505:in `call'
   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:81:in `run_callbacks'
   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.4/lib/abstract_controller/callbacks.rb:19:in `process_action'
   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.4/lib/action_controller/metal/rescue.rb:29:in `process_action'
   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.4/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/notifications.rb:164:in `block in instrument'
   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/notifications.rb:164:in `instrument'
   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.4/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.4/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
   vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.4/lib/abstract_controller/base.rb:137:in `process'
   vendor/bundle/ruby/2.2.0/gems/actionview-4.2.4/lib/action_view/rendering.rb:30:in `process'
   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.4/lib/action_controller/metal.rb:196:in `dispatch'
   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.4/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.4/lib/action_controller/metal.rb:237:in `block in action'
   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/routing/route_set.rb:76:in `call'
   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/routing/route_set.rb:76:in `dispatch'
   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/routing/route_set.rb:45:in `serve'
   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/journey/router.rb:43:in `block in serve'
   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/journey/router.rb:30:in `each'
   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/journey/router.rb:30:in `serve'
   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/routing/route_set.rb:821:in `call'
   vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-3.14.0.305/lib/new_relic/agent/instrumentation/middleware_tracing.rb:78:in `call'
   vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-3.14.0.305/lib/new_relic/rack/agent_hooks.rb:30:in `traced_call'
   vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-3.14.0.305/lib/new_relic/agent/instrumentation/middleware_tracing.rb:78:in `call'
   vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-3.14.0.305/lib/new_relic/rack/browser_monitoring.rb:32:in `traced_call'
   vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-3.14.0.305/lib/new_relic/agent/instrumentation/middleware_tracing.rb:78:in `call'
   vendor/bundle/ruby/2.2.0/gems/bounscale-0.0.4/lib/bounscale/middlerware.rb:23:in `call'
   vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-3.14.0.305/lib/new_relic/agent/instrumentation/middleware_tracing.rb:78:in `call'
   vendor/bundle/ruby/2.2.0/gems/warden-1.2.3/lib/warden/manager.rb:35:in `block in call'
   vendor/bundle/ruby/2.2.0/gems/warden-1.2.3/lib/warden/manager.rb:34:in `catch'
   vendor/bundle/ruby/2.2.0/gems/warden-1.2.3/lib/warden/manager.rb:34:in `call'
   vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-3.14.0.305/lib/new_relic/agent/instrumentation/middleware_tracing.rb:78:in `call'
   vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/etag.rb:24:in `call'
   vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-3.14.0.305/lib/new_relic/agent/instrumentation/middleware_tracing.rb:78:in `call'
   vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/conditionalget.rb:38:in `call'
   vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-3.14.0.305/lib/new_relic/agent/instrumentation/middleware_tracing.rb:78:in `call'
   vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
   vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-3.14.0.305/lib/new_relic/agent/instrumentation/middleware_tracing.rb:78:in `call'
   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
   vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-3.14.0.305/lib/new_relic/agent/instrumentation/middleware_tracing.rb:78:in `call'
   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/flash.rb:260:in `call'
   vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-3.14.0.305/lib/new_relic/agent/instrumentation/middleware_tracing.rb:78:in `call'
   vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:225:in `context'
   vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:220:in `call'
   vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-3.14.0.305/lib/new_relic/agent/instrumentation/middleware_tracing.rb:78:in `call'
   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/cookies.rb:560:in `call'
   vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-3.14.0.305/lib/new_relic/agent/instrumentation/middleware_tracing.rb:78:in `call'
   vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/query_cache.rb:36:in `call'
   vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-3.14.0.305/lib/new_relic/agent/instrumentation/middleware_tracing.rb:78:in `call'
   vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
   vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-3.14.0.305/lib/new_relic/agent/instrumentation/middleware_tracing.rb:78:in `call'
   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:88:in `__run_callbacks__'
   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:81:in `run_callbacks'
   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
   vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-3.14.0.305/lib/new_relic/agent/instrumentation/middleware_tracing.rb:78:in `call'
   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
   vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-3.14.0.305/lib/new_relic/agent/instrumentation/middleware_tracing.rb:78:in `call'
   vendor/bundle/ruby/2.2.0/gems/raygun4ruby-1.1.8/lib/raygun/middleware/rails_insert_affected_user.rb:11:in `call'
   vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-3.14.0.305/lib/new_relic/agent/instrumentation/middleware_tracing.rb:78:in `call'
   vendor/bundle/ruby/2.2.0/gems/raygun4ruby-1.1.8/lib/raygun/middleware/rack_exception_interceptor.rb:10:in `call'
   vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-3.14.0.305/lib/new_relic/agent/instrumentation/middleware_tracing.rb:78:in `call'
   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
   vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-3.14.0.305/lib/new_relic/agent/instrumentation/middleware_tracing.rb:78:in `call'
   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
   vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-3.14.0.305/lib/new_relic/agent/instrumentation/middleware_tracing.rb:78:in `call'
   vendor/bundle/ruby/2.2.0/gems/railties-4.2.4/lib/rails/rack/logger.rb:38:in `call_app'
   vendor/bundle/ruby/2.2.0/gems/railties-4.2.4/lib/rails/rack/logger.rb:20:in `block in call'
   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/tagged_logging.rb:68:in `block in tagged'
   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/tagged_logging.rb:26:in `tagged'
   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/tagged_logging.rb:68:in `tagged'
   vendor/bundle/ruby/2.2.0/gems/railties-4.2.4/lib/rails/rack/logger.rb:20:in `call'
   vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-3.14.0.305/lib/new_relic/agent/instrumentation/middleware_tracing.rb:78:in `call'
   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/request_id.rb:21:in `call'
   vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-3.14.0.305/lib/new_relic/agent/instrumentation/middleware_tracing.rb:78:in `call'
   vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/methodoverride.rb:22:in `call'
   vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-3.14.0.305/lib/new_relic/agent/instrumentation/middleware_tracing.rb:78:in `call'
   vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/runtime.rb:18:in `call'
   vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-3.14.0.305/lib/new_relic/agent/instrumentation/middleware_tracing.rb:78:in `call'
   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
   vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-3.14.0.305/lib/new_relic/agent/instrumentation/middleware_tracing.rb:78:in `call'
   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/static.rb:116:in `call'
   vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-3.14.0.305/lib/new_relic/agent/instrumentation/middleware_tracing.rb:78:in `call'
   vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/sendfile.rb:113:in `call'
   vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-3.14.0.305/lib/new_relic/agent/instrumentation/middleware_tracing.rb:78:in `call'
   vendor/bundle/ruby/2.2.0/gems/railties-4.2.4/lib/rails/engine.rb:518:in `call'
   vendor/bundle/ruby/2.2.0/gems/railties-4.2.4/lib/rails/application.rb:165:in `call'
   vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-3.14.0.305/lib/new_relic/agent/instrumentation/middleware_tracing.rb:78:in `call'
   vendor/bundle/ruby/2.2.0/gems/puma-2.14.0/lib/puma/configuration.rb:78:in `call'
   vendor/bundle/ruby/2.2.0/gems/puma-2.14.0/lib/puma/server.rb:541:in `handle_request'
   vendor/bundle/ruby/2.2.0/gems/puma-2.14.0/lib/puma/server.rb:388:in `process_client'
   vendor/bundle/ruby/2.2.0/gems/puma-2.14.0/lib/puma/server.rb:270:in `block in run'
   vendor/bundle/ruby/2.2.0/gems/puma-2.14.0/lib/puma/thread_pool.rb:106:in `call'
   vendor/bundle/ruby/2.2.0/gems/puma-2.14.0/lib/puma/thread_pool.rb:106:in `block in spawn_thread'
```

**Comment by taragano** [comment]
I'm sorry for the long delay in my response.
Do you still experience this issue now? If so, please contact support@cloudinary.com with the timestamp of the request and we'll be happy to do our best and find some more information about it in our logs.

**Comment by taragano** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support http://support.cloudinary.com or create a new ticket if you have any additional issues
