### ISSUE TITLE
Active Storage Errors

### ISSUE THREAD

**Issue by andrew-oko-odion** [cloudinary/cloudinary_gem#363]
my `storage.yml ` 

```

cloudinary:      
  service: Cloudinary
  cloud_name: niceguy
  api_key: api_key
  api_secret: api_secret
  secure: true
  cdn_subdomain: true
  enhance_image_tag: true
  static_file_support: false
```

```
[ActiveJob] [ActiveStorage::AnalyzeJob] [0884871f-8fc9-4945-b79c-b23c97775eb2] Error performing ActiveStorage::AnalyzeJob (Job ID: 0884871f-8fc9-4945-b79c-b23c97775eb2) from Async(active_storage_analysis) in 5711.29ms: ActiveStorage::IntegrityError (ActiveStorage::IntegrityError):
/home/niceguy/.rvm/gems/ruby-2.6.3/gems/activestorage-6.0.0/lib/active_storage/downloader.rb:39:in `verify_integrity_of'
/home/niceguy/.rvm/gems/ruby-2.6.3/gems/activestorage-6.0.0/lib/active_storage/downloader.rb:14:in `block in open'
/home/niceguy/.rvm/gems/ruby-2.6.3/gems/activestorage-6.0.0/lib/active_storage/downloader.rb:24:in `open_tempfile'
/home/niceguy/.rvm/gems/ruby-2.6.3/gems/activestorage-6.0.0/lib/active_storage/downloader.rb:12:in `open'
/home/niceguy/.rvm/gems/ruby-2.6.3/gems/activestorage-6.0.0/lib/active_storage/service.rb:86:in `open'
/home/niceguy/.rvm/gems/ruby-2.6.3/gems/activestorage-6.0.0/app/models/active_storage/blob.rb:206:in `open'
/home/niceguy/.rvm/gems/ruby-2.6.3/gems/activestorage-6.0.0/lib/active_storage/analyzer.rb:27:in `download_blob_to_tempfile'
/home/niceguy/.rvm/gems/ruby-2.6.3/gems/activestorage-6.0.0/lib/active_storage/analyzer/image_analyzer.rb:32:in `read_image'
/home/niceguy/.rvm/gems/ruby-2.6.3/gems/activestorage-6.0.0/lib/active_storage/analyzer/image_analyzer.rb:21:in `metadata'
/home/niceguy/.rvm/gems/ruby-2.6.3/gems/activestorage-6.0.0/app/models/active_storage/blob/analyzable.rb:47:in `extract_metadata_via_analyzer'
/home/niceguy/.rvm/gems/ruby-2.6.3/gems/activestorage-6.0.0/app/models/active_storage/blob/analyzable.rb:29:in `analyze'
/home/niceguy/.rvm/gems/ruby-2.6.3/gems/activestorage-6.0.0/app/jobs/active_storage/analyze_job.rb:10:in `perform'
/home/niceguy/.rvm/gems/ruby-2.6.3/gems/activejob-6.0.0/lib/active_job/execution.rb:39:in `block in perform_now'
/home/niceguy/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.0/lib/active_support/callbacks.rb:112:in `block in run_callbacks'
/home/niceguy/.rvm/gems/ruby-2.6.3/gems/i18n-1.6.0/lib/i18n.rb:297:in `with_locale'
/home/niceguy/.rvm/gems/ruby-2.6.3/gems/activejob-6.0.0/lib/active_job/translation.rb:9:in `block (2 levels) in <module:Translation>'
/home/niceguy/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.0/lib/active_support/callbacks.rb:121:in `instance_exec'
/home/niceguy/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.0/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
/home/niceguy/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.0/lib/active_support/core_ext/time/zones.rb:66:in `use_zone'
/home/niceguy/.rvm/gems/ruby-2.6.3/gems/activejob-6.0.0/lib/active_job/timezones.rb:9:in `block (2 levels) in <module:Timezones>'
/home/niceguy/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.0/lib/active_support/callbacks.rb:121:in `instance_exec'
/home/niceguy/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.0/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
/home/niceguy/.rvm/gems/ruby-2.6.3/gems/activejob-6.0.0/lib/active_job/logging.rb:25:in `block (4 levels) in <module:Logging>'
/home/niceguy/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.0/lib/active_support/notifications.rb:180:in `block in instrument'
/home/niceguy/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.0/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/home/niceguy/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.0/lib/active_support/notifications.rb:180:in `instrument'
/home/niceguy/.rvm/gems/ruby-2.6.3/gems/activejob-6.0.0/lib/active_job/logging.rb:24:in `block (3 levels) in <module:Logging>'
/home/niceguy/.rvm/gems/ruby-2.6.3/gems/activejob-6.0.0/lib/active_job/logging.rb:45:in `block in tag_logger'
/home/niceguy/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.0/lib/active_support/tagged_logging.rb:80:in `block in tagged'
/home/niceguy/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.0/lib/active_support/tagged_logging.rb:28:in `tagged'
/home/niceguy/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.0/lib/active_support/tagged_logging.rb:80:in `tagged'
/home/niceguy/.rvm/gems/ruby-2.6.3/gems/activejob-6.0.0/lib/active_job/logging.rb:45:in `tag_logger'
/home/niceguy/.rvm/gems/ruby-2.6.3/gems/activejob-6.0.0/lib/active_job/logging.rb:21:in `block (2 levels) in <module:Logging>'
/home/niceguy/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.0/lib/active_support/callbacks.rb:121:in `instance_exec'
/home/niceguy/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.0/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
/home/niceguy/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.0/lib/active_support/callbacks.rb:139:in `run_callbacks'
/home/niceguy/.rvm/gems/ruby-2.6.3/gems/activejob-6.0.0/lib/active_job/execution.rb:38:in `perform_now'
/home/niceguy/.rvm/gems/ruby-2.6.3/gems/activejob-6.0.0/lib/active_job/execution.rb:24:in `block in execute'
/home/niceguy/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.0/lib/active_support/callbacks.rb:112:in `block in run_callbacks'
/home/niceguy/.rvm/gems/ruby-2.6.3/gems/activejob-6.0.0/lib/active_job/railtie.rb:43:in `block (4 levels) in <class:Railtie>'
/home/niceguy/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.0/lib/active_support/execution_wrapper.rb:88:in `wrap'
/home/niceguy/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.0/lib/active_support/reloader.rb:72:in `block in wrap'
/home/niceguy/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.0/lib/active_support/execution_wrapper.rb:88:in `wrap'
/home/niceguy/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.0/lib/active_support/reloader.rb:71:in `wrap'
/home/niceguy/.rvm/gems/ruby-2.6.3/gems/activejob-6.0.0/lib/active_job/railtie.rb:42:in `block (3 levels) in <class:Railtie>'
/home/niceguy/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.0/lib/active_support/callbacks.rb:121:in `instance_exec'
/home/niceguy/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.0/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
/home/niceguy/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.0/lib/active_support/callbacks.rb:139:in `run_callbacks'
/home/niceguy/.rvm/gems/ruby-2.6.3/gems/activejob-6.0.0/lib/active_job/execution.rb:22:in `execute'
/home/niceguy/.rvm/gems/ruby-2.6.3/gems/activejob-6.0.0/lib/active_job/queue_adapters/async_adapter.rb:70:in `perform'
/home/niceguy/.rvm/gems/ruby-2.6.3/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/safe_task_executor.rb:24:in `block in execute'
/home/niceguy/.rvm/gems/ruby-2.6.3/gems/concurrent-ruby-1.1.5/lib/concurrent/synchronization/mutex_lockable_object.rb:41:in `block in synchronize'
/home/niceguy/.rvm/gems/ruby-2.6.3/gems/concurrent-ruby-1.1.5/lib/concurrent/synchronization/mutex_lockable_object.rb:41:in `synchronize'
/home/niceguy/.rvm/gems/ruby-2.6.3/gems/concurrent-ruby-1.1.5/lib/concurrent/synchronization/mutex_lockable_object.rb:41:in `synchronize'
/home/niceguy/.rvm/gems/ruby-2.6.3/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/safe_task_executor.rb:19:in `execute'
/home/niceguy/.rvm/gems/ruby-2.6.3/gems/concurrent-ruby-1.1.5/lib/concurrent/ivar.rb:169:in `safe_execute'
/home/niceguy/.rvm/gems/ruby-2.6.3/gems/concurrent-ruby-1.1.5/lib/concurrent/scheduled_task.rb:285:in `process_task'
/home/niceguy/.rvm/gems/ruby-2.6.3/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/timer_set.rb:166:in `block (2 levels) in process_tasks'
/home/niceguy/.rvm/gems/ruby-2.6.3/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/home/niceguy/.rvm/gems/ruby-2.6.3/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/home/niceguy/.rvm/gems/ruby-2.6.3/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/home/niceguy/.rvm/gems/ruby-2.6.3/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/home/niceguy/.rvm/gems/ruby-2.6.3/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/home/niceguy/.rvm/gems/ruby-2.6.3/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
[ActiveJob] Enqueued ActiveStorage::AnalyzeJob (Job ID: 0884871f-8fc9-4945-b79c-b23c97775eb2) to Async(active_storage_analysis) at 2019-10-08 20:31:06 UTC with arguments: #<GlobalID:0x00007f49100862a8 @uri=#<URI::GID gid://rest-api/ActiveStorage::Blob/62>>
Retrying ActiveStorage::AnalyzeJob in 627 seconds, due to a ActiveStorage::IntegrityError.
```

**Comment by andrew-oko-odion** [comment]
this is happen on rails 6

**Comment by andrew-oko-odion** [comment]
yes, your are right I figured it out
the gem works perfectly... 

in  my case, some part of the code was attempting to `purge existing avatar` before 
uploading another one Which was very wrong because `has_one_attached :avatar` already handles that.

**Comment by andrew-oko-odion** [comment]
We can close this now
